### ISSUE TITLE
Updated binaries

### ISSUE THREAD

**Issue by mubix** [maaaaz/impacket-examples-windows#1]
Any chance you can update the binaries, or at least just secrets dump. @asolino has made some cool updates

**Comment by maaaaz** [comment]
Hello @mubix,

Sure, I just pushed several updated binaries, among `secretsdump.exe`: check the [release information](https://github.com/maaaaz/impacket-examples-windows/releases/tag/v0.9.14_updated_06052016) for the full list.

Cheers !

**Comment by mubix** [comment]
Awesome! Thanks!

**Comment by anonymouz4** [comment]
I've compiled SimpleHTTPServer from the newest version
and also updated SMBServer.exe
The old smbserver.exe didn't have the port feature, so when the windows smb fileshare is running, you can't bind two times the same port.

[SimpleHTTPServer.exe.zip](https://github.com/maaaaz/impacket-examples-windows/files/2902164/SimpleHTTPServer.exe.zip)
[smbserver.exe.zip](https://github.com/maaaaz/impacket-examples-windows/files/2902165/smbserver.exe.zip)
